@echo off
echo Starting Car Service Center Backend...
cd backend
echo Installing Python dependencies...
pip install -r requirements.txt
echo Starting FastAPI server...
uvicorn main:app --reload --host 0.0.0.0 --port 8000
pause